"""orders table

Revision ID: 4e876c8f45f8
Revises: 56e819843738
Create Date: 2025-07-04 09:12:27.747672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e876c8f45f8'
down_revision: Union[str, None] = '56e819843738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('tracking_id', sa.Uuid(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CREDIT_CARD', 'SBP', name='paymentmethod'), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_tracking_id'), 'orders', ['tracking_id'], unique=True)
    op.add_column('items', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'order_id')
    op.drop_index(op.f('ix_orders_tracking_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
