"""upgraded tables

Revision ID: 8a216a28a1cf
Revises: e8a4e2290c07
Create Date: 2025-06-17 15:51:59.893760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a216a28a1cf'
down_revision: Union[str, None] = 'e8a4e2290c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('products_item_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('products_item_id_fkey'), 'products', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'product_id')
    # ### end Alembic commands ###
