"""bug fixed

Revision ID: d7c5936fe439
Revises: 8a216a28a1cf
Create Date: 2025-06-17 15:55:46.127640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c5936fe439'
down_revision: Union[str, None] = '8a216a28a1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_product_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'product_id')
    op.add_column('products', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'item_id')
    op.add_column('items', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('items_product_id_fkey'), 'items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
