"""update

Revision ID: 20d7bc453faa
Revises: 4e876c8f45f8
Create Date: 2025-07-04 11:09:05.034604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d7bc453faa'
down_revision: Union[str, None] = '4e876c8f45f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'cart_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
